### PR TITLE
Added arXiver slides

### PR DESCRIPTION
**Pull request by cosmicpudding**
I'm githubbing!

### CODE REVIEW

**Comment by Cadair** [comment]
:+1:

**Comment by cosmicpudding** [comment]
^_^ #githubeverything

**Comment by Cadair** [comment]
:fireworks:

**Comment by cosmicpudding** [comment]
Haha how do I favourite a github comment? That should totally be a thing if it's not already...!

**Comment by PBarmby** [comment]
Thanks Vanessa!

**Comment by Cadair** [comment]
@astrofrog +infinity

**Comment by cosmicpudding** [comment]
Is that really a thing? +infinity seems dangerous...

**Comment by Cadair** [comment]
with great power...

**Comment by cosmicpudding** [comment]
@Cadair +(1/0.)

**Comment by Cadair** [comment]
bonus points for explicitly using float division rather than assuming Python 3. :p

**Comment by astrofrog** [comment]
I discovered recently that one can do `float('inf')` too. And I also didn't know there is a pure-Python `NaN` value (`float('nan')`)...

**Pull request merged**
